ALTER TABLE chat_groups ADD COLUMN IF NOT EXISTS description VARCHAR(1000);
ALTER TABLE chat_groups ADD COLUMN IF NOT EXISTS rules VARCHAR(2000);
ALTER TABLE chat_groups ADD COLUMN IF NOT EXISTS is_public BOOLEAN DEFAULT FALSE;
